name: CVE Scanning for Node.js

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  pull_request:
    paths:
      - 'package.json'
      - 'website/package.json'
      - 'package-lock.json'
      - '.github/fixtures/cve-whitelist.json'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prod
      - run: npx --yes auditjs ossi --whitelist .github/fixtures/cve-whitelist.json
