name: Build and Publish Docker Image

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  docker-build-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Log in to Docker Hub
        if: github.repository == 'finos/git-proxy'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: finos
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Tag
        id: tags
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tags=finos/git-proxy:${{ github.ref_name }},finos/git-proxy:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=finos/git-proxy:main" >> $GITHUB_OUTPUT
          fi

      - name: Build and Publish Docker Image
        if: github.repository == 'finos/git-proxy'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          provenance: true
