name: 'Unused Dependencies'
on: [pull_request]

permissions: 
  contents: read 

jobs:
  unused-dependecies:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: '18.x'
      - name: 'Run depcheck'
        run: | 
          npx depcheck --skip-missing --ignores="@babel/*,@commitlint/*,eslint,eslint-*,husky,mocha,concurrently,nyc,prettier,typescript,vite-tsconfig-paths"
          echo $?
          if [[ $? == 1 ]]; then
            echo "Unused dependencies or devDependencies found"
            exit 1
          fi

