name: 'Unused Dependencies'
on: [pull_request]

permissions:
  contents: read

jobs:
  unused-dependecies:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: 'Setup Node.js'
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22.x'
      - name: 'Run depcheck'
        run: |
          npx depcheck --skip-missing --ignores="tsx,@babel/*,@commitlint/*,eslint,eslint-*,husky,ts-node,concurrently,nyc,prettier,typescript,tsconfig-paths,vite-tsconfig-paths,quicktype,history,@types/domutils,@vitest/coverage-v8,cross-env"
          echo $?
          if [[ $? == 1 ]]; then
            echo "Unused dependencies or devDependencies found"
            exit 1
          fi
